baseURL = "https://www.oorkan.dev/"
languageCode = "en-us"
title = "oorkan"
theme = "contrast-hugo-mod"
paginate = 15
pygmentsUseClasses = true

#[menu]
#    [[menu.social]]
#        identifier = "twitter"
#        name = "twitter"
#        pre = "<i class='fa fa-twitter'></i>"
#        url = "#"
#    
#    [[menu.social]]
#        identifier = "github"
#        name = "github"
#        pre = "<i class='fa fa-github'></i>"
#        url = "#"

pluralizelisttitles = "false"

[params]
    logo = "https://res.cloudinary.com/oorkan/image/upload/v1609088270/blog/img/general/logo_rjw6md.jpg"
    gid = "UA-176760402-2"
    darkMode = true
