baseURL = "https://www.oorkan.dev/"
languageCode = "en-us"
title = "oorkan"
theme = "contrast-hugo-mod"
paginate = 20

#[menu]
#    [[menu.social]]
#        identifier = "twitter"
#        name = "twitter"
#        pre = "<i class='fa fa-twitter'></i>"
#        url = "#"
#    
#    [[menu.social]]
#        identifier = "github"
#        name = "github"
#        pre = "<i class='fa fa-github'></i>"
#        url = "#"

pluralizelisttitles = "false"

[params]
    gid = "UA-176760402-2"
