version: "3"

services:
  hugo:
    image: chainguard/hugo:latest
    user: "1000:1000"
    working_dir: /srv/hugo
    volumes:
      - .:/srv/hugo
    command: "server --bind 0.0.0.0 --baseURL http://${WLAN_IP:-localhost} --templateMetrics ${SERVE_DRAFTS:--D}"
    ports:
      - 1313:1313
