version: "3"

services:
  hugo:
    image: chainguard/hugo:latest
    working_dir: /srv/hugo
    volumes:
      - .:/srv/hugo
    command: "server --bind 0.0.0.0 --templateMetrics -D"
    ports:
      - 1313:1313